### ISSUE TITLE
Feature: Saving individual images to a SD card

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#10]
For me stacking is not so highly important. Just saving images to a SD card would be nice. Stacking can be done later. Having a 32 gbyte SD card would allow to store about 900 images of 32mbytes. Assuming the exposure time is 6 seconds for unguided images plus a few seconds for downloading. That would allow about 9000 seconds or 2.5 hours exposing. Stacking and filtering of the good and bad images can be done later and better.

**Comment by artyom-beilis** [comment]
Should be possible in beta7 by moving app to the external storage from Applications->OpenLiveStacker->Storage->Change

**Comment by artyom-beilis** [comment]
Didn't work...

- moving to SD Cart prevents from astap ranning
- it still uses DCIM at normal locatiion

**Comment by artyom-beilis** [comment]
Implemented in Beta9
