### ISSUE TITLE
App keep on running but not detected as application

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#11]
Saw this morning it is still active:
![Screenshot_20230427-100623_Samsung Experience Home](https://user-images.githubusercontent.com/46811539/234826622-5f8e8779-8c74-4c22-9eb5-ccf7c68977c1.jpg)

A few seconds later. Still active. Time has increased
![Screenshot_20230427-100639_Samsung Experience Home](https://user-images.githubusercontent.com/46811539/234826730-fe09f307-42f9-476d-adc8-46e443f0818a.jpg)

But it say no app active.
![Screenshot_20230427-100709_Samsung Experience Home](https://user-images.githubusercontent.com/46811539/234826748-67190ace-869c-4a97-865c-9b885090bc01.jpg)

This is what I see if the app is still hidden running. When I start the app I can only exit:
![Screenshot_20230427-101031](https://user-images.githubusercontent.com/46811539/234826856-09242582-bacb-4075-9cb1-ffb406fcd00b.jpg)

**Comment by artyom-beilis** [comment]
You need to close it with "Close and Exit"

It is designed to run in background since the image capturing/EAA session can be long.

**Comment by artyom-beilis** [comment]
So I'm closing it.
