### ISSUE TITLE
Strange error when I try camera connect

### ISSUE THREAD

**Issue by aka4el** [artyom-beilis/OpenLiveStacker#110]
tried both the SVBony sv305c and the Defender c-110 webcam
connected to a Samsung A22 (13 android) via a USB type C OTG 3.0 adapter
the program sees both cameras, but refuses to work with them due to an incomprehensible error

what am i doing wrong?

![Screenshot_20241226_202734](https://github.com/user-attachments/assets/41e4e2dd-9b15-4de8-9bc4-4c4d35165273)
![Screenshot_20241226_202035](https://github.com/user-attachments/assets/c065a7e7-aef4-46bd-a912-271f5418afab)

**Comment by artyom-beilis** [comment]
SVBony sv305 is not supported - it is not UVC (USB Video Class) camera - only 205/105 are UVC

Regarding Web Cam - you need to use "UVC" driver not touptek

**Comment by artyom-beilis** [comment]
Note: SVBony hand't released SDK for Android so it is impossible to support sv305 and other non UVC cameras

**Comment by aka4el** [comment]
**artyom-beilis**
Thank you, it's all very clear. It's not about the program, but about the efficiency of the device supplier
