### ISSUE TITLE
Feature: report write disk error when disk is full.

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#12]
When my phone disk is full, the debug files are written with 8 bytes only. For files see link in Cloudynights forum. 

I assume it would be easy to detect and report a "write disk error".

**Comment by artyom-beilis** [comment]
I needed need to build error notifications channel.

I explain. Almost all stacking control operations are asynchronous. That means it all run in different threads in background.

I need to build a error notifications push system that would send a error to the browser telling something goes wrong for asynchronous events.

**Comment by artyom-beilis** [comment]
Fixed in 
2d52034
