### ISSUE TITLE
Starting the application has to be done twice.

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#19]
Just run the version 8.

There is still an old problem which could confuse users. When I start the application I have to do the following:

Run application:

1) Accept "access to USB port".
2) Accept "access to USB port" again.
3) Select "ASI device" does not do anything. So I "Close and exit" the application.
4) Run the application for the second time
5) Select "ASI device".

Then it runs

**Comment by artyom-beilis** [comment]
Interesting. This is something need to be checked. But I don't know how. Probably I need to find some VM images that support OTG and Android 8...

Strange behaviour indeed.

**Comment by han-k59** [comment]
Does not happen in beta 9.1. I will close it
