### ISSUE TITLE
Pixel 6 pro requires resolution 480x640 added to dropdown

### ISSUE THREAD

**Issue by bugcatcher75** [artyom-beilis/OpenLiveStacker#2]
Tested with pixel 6 pro
Ucb3 controller + camera(asi462mc) + ucb3 connector on end of ucb3 controller to connect to pixel 6 phone.
Tested with asicap and no issues on 640x480 but all other higher resolutions show problems in capture of video (green streaks)

Suggested fix;
Add option to select 640x480 and maybe it will work better.

I have tried all resolutions in this app and seems i get a white screen mostly.  App does generate files of the white screen.  However when I change the physical lighting on the camera(cover camera or let lots of light) i don't see any change in apps view.

Blocked on testing further on pixel 6. 
Going to try another android device but maybe to old version Samsung 10 years old.

Steps:
1.  Turn pixel 6 on and connect to USB controller using usb3-c connector to ucb3 inflow to USB controller(powered).
2. Connect camera to USB controller.
3. Start up app
4. Connect to asi462ms camera
5. Set resolution to anything and then choose new stack name and pick M51 as object.  Set all fields related to calibration darks Flats to na.
6. Or click stream on setting and white screen will displayed.

Could not get any change to be displayed

Originally without any powered USB controller it did work(meaning seen changes to the view when allowing more light to the sensor, but camera was under powered when only relying  on power from cellphone.  I will repeat test once cellphone is 100 powered.

Please let me know if you need a sample white tiff file uploaded.
Generated or any debug files from clicking debug in settings.

Cable for camera was original cable came with camera.

**Comment by bugcatcher75** [comment]
Update.
Retested on lowest resolution with no USB controller and works.  Changed exposure to 1ms and noticed variations in light.  Next test will be with telescope.
Areas to test again:
Getting a real picture of stars focused and using plates over tool.
Confirm download of raw files can be used to process a image 
Review other areas of GUI related to stack features like stretch results.
Unblocked for now.

**Comment by bugcatcher75** [comment]
Closing issue as it was a misconfiguration.  Not sure if the exposure values are amplified as 1ms for exposure and gain set to 100.  Maybe gain is too high possibly.  Reviewing gain levels in app once on telescope.

**Comment by bugcatcher75** [comment]
Final comment.  Tested resolutions again.  Reproduced green streak issues on high resolution option inside this app.  Hoping more resolution options can be returned from the camera as this app seems to stop for the top 3 (within each category(mono vs bit ratio etc).
If more resolutions can be downloaded please reply and I will wait for next release to retest.
So it seems the green streak flashing could be related to pixel or usb-3 connector or a bug in asicap's software originally but workaround is 640x480 resolution on pixel 6.

**Comment by artyom-beilis** [comment]
Few things. 

- ASICap and openlivestacker build around same sdk. However note that asicap doesn't expose 16bit mode. Only 8 bit.
- regarding size. The downscale is actually binning. Only way to reduce the size and transfer is use ROI and reduce camera FOV.

I recommend using longer exposure since it reduces pressure of framerate and fast data transfer. I usually have at least 200ms-500ms. Finally it isn't a PC with ultra fast usb3 ports. Usually it is usb2 but for DSO it is usually more than enough

**Comment by bugcatcher75** [comment]
Ok. Thanks for direction.  I will continue to test with 100ms or higher.  I will also check the bin options as well.  
Pixel 6 native photo app picks up the tiff files but cannot load them.  I have a tiff viewer app to verify.

**Comment by artyom-beilis** [comment]
Regarding tuff

**Comment by artyom-beilis** [comment]
Regarding tiff saved in stacked dir. It is 16bit image after stacking without any post-processing. So you can work with it offline. The jpeg is one that is stretched
