### ISSUE TITLE
Zooming/focusing using internal browser

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#22]
The internal browser can not zoom in when streaming. This making focusing very difficult. The external browser can zoom.  One way around it is to allow a higher zoom factor in the APP.

**Comment by han-k59** [comment]
In the internal browser zooming using two vingers is not working. The x2  x4 zooming is working but is not enough to see stars good enough.

What a good solution would be is reading only a sub section of the stream. Eg 25% or 500 x500 pixel of the center, 10% or 200 x200 pixels.

**Comment by artyom-beilis** [comment]
Are you using pinch zoom or pressing +/- in the left/bottom corner.

I had so many issues in the past with pinch zoom and browser compatibility on AstroHopper that is also sometimes depends on specific browser settings so I did something much simpler to get it going till I implement pinch based zoo that at least is consistent.

In some browsers you can pinch zoom - but it is native built in zoom - not app zoom.

> I also have the impression that the auto stretch is not working for streaming.

Auto and manual stretch are for stacking only. But it is actually not a bad idea to add an option of autostrech for live stream as well.

**Comment by han-k59** [comment]
I'm using two fingers for zooming. Just option to select a part of the center (25%, 10%) looks for me the best option. Focusing is best done at center of the image not at the corners where more optical errors are visible.

**Comment by han-k59** [comment]
Downloading only a section of the image would speed up. You want fast feedback if your manually adjusting the focus.

**Comment by artyom-beilis** [comment]
Closing it since there other better ticket you opened #31
