### ISSUE TITLE
Add support for smartphone's native camera

### ISSUE THREAD

**Issue by givoly** [artyom-beilis/OpenLiveStacker#26]
It would be great to be able to use the native camera of the phone - this could be either directly by observing the sky (wide field) or by connecting it to a telescope in eyepiece projection mode - in any case, it would allow using the software without any separate ZWO or SVBONY dedicated astronomy camera. Of course, this may be limited to brighter objects. However, it is worth the limitation to make it accessible to many more people.

There are, of course, limitations and many differences between smartphone camera features/capabilities - so the parameters should be configurable within the range. Important is to be able to control the focus of the camera - which is not an issue with connecting to other cameras. So having ability to set focus will be required addition as well.

**Comment by artyom-beilis** [comment]
Implemented in beta24
