### ISSUE TITLE
Solver screen is not readable

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#28]
See attached video and screenshot. Displayed values overlap and are not readable.

![XRecorderLite_23052023_234819](https://github.com/artyom-beilis/OpenLiveStacker/assets/46811539/a186942a-d336-4c54-81f3-30a255639afa)

https://github.com/artyom-beilis/OpenLiveStacker/assets/46811539/a6d9221f-7ed1-4099-a679-e51f28e1084e

**Comment by artyom-beilis** [comment]
![image](https://github.com/artyom-beilis/OpenLiveStacker/assets/14816918/fdab2bd2-a2d0-422d-9a13-3d9993c18d6e)

The new look
