### ISSUE TITLE
Stacking produces an image containing only value zero

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#3]
With my ASI1600 camera, S7 phone and Android 8,  streaming works but stacking produces TIFF files where all pixels have value 0. Attached some log files.

[OpenliveStacker3.zip](https://github.com/artyom-beilis/OpenLiveStacker/files/11324413/OpenliveStacker3.zip)

**Comment by artyom-beilis** [comment]
Can you please record several frames - i.e. set "Save Debug" during stacking and do a very short few frames stack.

Under debug directory you'll see the raw (tiff) images before stacking I can analize.

It seems there is some kind of bug regarding handling mono camera (since I don't own)

BTW. Do you have Linux? Because it may be way simpler to debug this kind of stuff directly on Linux rather then Android.

**Comment by artyom-beilis** [comment]
After reviewing the code once again. I really need to see the tiff frames saved via debug (very short stack)

**Comment by han-k59** [comment]
Stacking of the simulated image M44 works. In debug folder  I can see the individual images

Still have some problem with starting the app. It asks twice to allow using the USB. Then nothing happens. After close it seems to work with ASI selection, but didn't got an astro image yet. Phone battery is empty now and I'm recharging now

**Comment by han-k59** [comment]
In  debug mode the frame are written correctly. Also stack seems to work but no stack file is produced. So there are the follwing problems:

1) Still have some problem with starting the app. It asks twice to allow using the USB. Then nothing happens. After close it  work swith ASI selection.

2) Stream stay green. No sky image is shown.

3) Stacking.  Sky images are made and written to debug folder !!!. See attached.

4) No stack result is found in folder stack.

5) After return, the camera is not functioning anymore. No respons.  Application show only menu option EXIT.  After restart  camera no response.  Restart  openlivestacker application plus briefly decoupling USB  cable camera is required to restart

Some images plus logs:
[OpenliveStacker5.zip](https://github.com/artyom-beilis/OpenLiveStacker/files/11327218/OpenliveStacker5.zip)

**Comment by han-k59** [comment]
Here a screenshot of the stacking

![Screenshot_20230425-234912_Samsung Internet](https://user-images.githubusercontent.com/46811539/234416742-b18a2f03-edab-4398-981a-1c27011907eb.jpg)

**Comment by artyom-beilis** [comment]
In order to save the result you need to press "Save" button. It stops the stacking and saves the result.

**Comment by han-k59** [comment]
The strange thing stacking seems to work within simulation, but not with my ASI1600 images. The stack folder was empty but I had 5 folder with debug images.

Therefore it would be nice to set a path to a simulation image (see other issue). Maybe it has something with image size or being mono.

**Comment by han-k59** [comment]
For me stacking is not so highly important.  Just saving images to a SD card would be nice. Stacking can be done later. Having a 32 gbyte SD card would allow to store about 900 images of 32mbytes. Assuming the exposure time is 6 seconds plus a few seconds for downloading. That would allow 9000 seconds or 2.5 hours exposing. Stacking and filtering of the good and bad images can be done later. 

A second phone with a guide app would make it even better :)

**Comment by artyom-beilis** [comment]
> The strange thing stacking seems to work within simulation, but not with my ASI1600 images. The stack folder was empty but I had 5 folder with debug images.
> 
> Therefore it would be nice to set a path to a simulation image (see other issue). Maybe it has something to do with the image size or being mono.

Please collect logs and debug images.

Generally when you press "save" icon the stacking finished and result is saved. We are back to live video view.

You can also "pause" the stacking to review result before pressing save.

**Comment by han-k59** [comment]
I did some more testing. Often it does not work and I'm pretty sure it is the communication with the camera. The stacking gets more reliable with the camera is set at bin4x4 8 bit, so the smallest size.  Not with the full size 4656x 3520 pixel, 16 bit.

Anyhow if it work, I get stack and can save them. They do contain camera noise. So i assume the zero values where from a camera failure/communication failure. Attached the logs and below one image where communication stopped halfway.

[OpenliveStacker6.zip](https://github.com/artyom-beilis/OpenLiveStacker/files/11331668/OpenliveStacker6.zip)


![Untitled](https://user-images.githubusercontent.com/46811539/234547650-36c74c6b-8009-4d75-80c9-11393f1b2805.png)

**Comment by artyom-beilis** [comment]
It may also be registration issue.

Please record frames (with save) so I can run it offline

Also note I see that it seems with large frames 4656x3520 processing time is too large:

```log.txt.6:2023-04-26 11:39:21; stacker, info: Preprocessing took 436.72ms (processors.cpp:43)
log.txt.6:2023-04-26 11:39:24; stacker, info: Stacking took 1464.68 ms, generation 1292.35 ms, jpeg took=685.633 (processors.cpp:445)
```
It takes 1.5s registration and stacking. 1.2s postprocessing (stretch) and 0.6s jpeg compression (i.e. generation of live stream)

Sometimes in log I see numbers like these:

```
Stacking took 4872.48 ms, generation 1310.74 ms, jpeg took=1628.24 (processors.cpp:445)
```

So unless you have exposure times of maybe 5-10 seconds I don't see how processing power of the smartphone can handle full frame.

I think need to add support of ROI for ASI cameras of an object you are capturing is small.

Also for live stacking there is no reason to have something more than full HD frame (like 1920x1080) since you anyway will be limited by screen size.

**Comment by han-k59** [comment]
Attached some more star images in bin2x2 from yesterday. 
position : 13: 20 38.9	+75° 48 01	
FOV (height) about 1.3 degrees. So FL=580 mm, Pixel size 5.6 micrometer

Binning 1x1 is too much, but binning 2x2 like attached would be normal for the typical seeing. Sensor cooling is off  so the images are much more noisy then usual. Exposure time, i can't remember but a few seconds.

I would see ROI as a last remedy. Better not to use it.

[OpenliveStacker5b.zip](https://github.com/artyom-beilis/OpenLiveStacker/files/11332773/OpenliveStacker5b.zip)

You said something about test a Linux version. I can boot my PC to Linux next to my telescope.

**Comment by artyom-beilis** [comment]
![Clearsky2_Trst2_20230425_234810_stacked](https://user-images.githubusercontent.com/14816918/234581307-28c30cd4-3317-4b06-aacf-ec071f9dfbbf.jpeg)

Here is the stacking of 3 images result

**Comment by han-k59** [comment]
There where 11 images saved. I tried to copy them to my old Mac laptop running Windows on a small partition but was running out of disk space. So I saved only three images. I did delete the others from the phone also to make some space. So an option to save the images to SD would be nice.

A soon it is clear sky I will make new images. Then with camera cooling on and pointed to an interesting object.

**Comment by artyom-beilis** [comment]
>  So an option to save the images to SD would be nice.

Ok this is indeed important. I got you.

> Then with camera cooling on and pointed to an interesting object.

Which reminds me to add cooling/temperature controls and not only Gain + Exposure for ASI.

**Comment by artyom-beilis** [comment]
> It requires an setpoint (:

If so I'll add this feature and I'll have somebody to test it `:-)`

**Comment by artyom-beilis** [comment]
> Yes forgot that. Applying 12VDC to the camera is not enough. It requires an setpoint (:

Added it into beta6.

Also did some rework on controls. Apparently ASI camera starts with auto exposure and white balance and I didn't disabled them.

So one you can please check cooler controls. I don't have cooled camera so your help will be very important
