### ISSUE TITLE
Using ASI camera, the last used gain, format and exposure are not remembered.   

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#32]
1) Exposure time is remembered in simulation. But using the ASI1600 the last used gain, format, exposur end Auto Str. are not remembered.
2) Suggest to make Auto Str. default on.

**Comment by artyom-beilis** [comment]
> Exposure time is remembered in simulation. 

It isn't, it is just fixed to 1s

This is what profiles are for. 

Configure all parameters for the camera, save it as profile and once you open the camera load the profile.

See: https://github.com/artyom-beilis/OpenLiveStacker/wiki/Open-Live-Stacker-Manual#camera-profiles

I'm closing it meanwhile.
