### ISSUE TITLE
Using the SD card option givesl a runtime error after a second restart.

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#33]
Using the SD card option givesl a runtime error after a second restart.
![XRecorderLite_03062023_092945](https://github.com/artyom-beilis/OpenLiveStacker/assets/46811539/6768d5a3-18c5-470d-b0e2-bc1e3fc6b870)

**Comment by artyom-beilis** [comment]
Can you please check if the file test.txt in Android/media/org.openlivestacker/OpenLiveStacker directory exists

I try to create and delete the file to ensure that there are permissions to access the files:

https://github.com/artyom-beilis/android_live_stacker/blob/web_ols/app/src/main/java/org/openlivestacker/LiveStackerMain.java#L692

If it exists but not deleted, try to delete and see what happens.

**Comment by artyom-beilis** [comment]
BTW, was the keyboard "-" sign was fixed or not?

**Comment by artyom-beilis** [comment]
Can you please check with latest version. I added a more detailed error information.

**Comment by han-k59** [comment]
Yes beta version15 works fine with SD card. No more errors.

> BTW, was the keyboard "-" sign was fixed or not?
Yes fixed.

**Comment by artyom-beilis** [comment]
> Yes beta version15 works fine with SD card. No more errors.

What???? But I changed nothing :-/

**Comment by han-k59** [comment]
I have run the program probably 10 times and no error occurred.   The files are written to the SD card. I have checked that also.

Is there anything that could have fixed it? Permissions? This version starts without asking for permissions.  Only once for USB.

**Comment by artyom-beilis** [comment]
I'm glad to hear. Thanks! Mysterious ways of Android.

On android most permissions are asked only once. And for external device each time you connect/disconnect. So for example if you restart the app without disconnecting camera it wouldn't ask.
