### ISSUE TITLE
Field-of-view is halved when using bin2x2 format.

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#34]
For format "4656x3520,  bin 1x1" my field-of-view is about 13 degrees.

For format "2328 x1760,  bin 2x2", my field-of-view halves to about 6.5 degrees.

**Comment by artyom-beilis** [comment]
Are you referring for FOV calculations of solver, or actual FOV of camera?

i.e. when I calculate FOV of solver I don't take in account the binning - i.e. I don't multiply pixel size by value of bin

**Comment by han-k59** [comment]
The actual FOV is halved. I had problems with solving. Then I  uploaded the 2328 x1760 format image to nova.astrometry.net and noted the height in degrees is half.  So somehow the ROI is doing it.

You can see it in the video. The trees in the corner disappears in 2328 x1760 format. Strange enough the solver adapts (based on pixel size and focal length) So it must be the ROI.

**Comment by artyom-beilis** [comment]
The actual issues is that I don't take in account binning. So when I recalculate FOV using pixel size * height I get incorrect result. I checked FOV once again with my 224MC and it works as expected.
