### ISSUE TITLE
Menu titles are wrapping

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#4]
Menu titles are wrapping. For example to pixel size and focal length titles. See attached screenshots

![Screenshot_20230425-153027_Samsung Internet](https://user-images.githubusercontent.com/46811539/234340352-e9074591-3181-4eb9-a3d4-d87a47d26930.jpg)

![Screenshot_20230424-090741_Samsung Internet](https://user-images.githubusercontent.com/46811539/234340386-f169860c-d969-4311-a6c7-0606d834e665.jpg)

**Comment by artyom-beilis** [comment]
What browser is that?

**Comment by han-k59** [comment]
The standard Samsung browser

**Comment by artyom-beilis** [comment]
Should be solved in beta7

**Comment by han-k59** [comment]
Thanks,

I will test it tonight. I will also release a new version of astap_cli. The astap_cli version your using, 2023-03-17 is not fully adapted to the new databases D05, D20, D50 and G05 which where released a few days later. It would be better to include this new astap_cli. 

Han

**Comment by artyom-beilis** [comment]
Can you please also build astap_cli for Android as x86 and x86\_64 and not only ARM since for simulators it mostly x86 or x86\_64 and it is highly useful.

> 2023-03-17 is not fully adapted to the new databases D05, D20

Actually I'm using it with D05.

**Comment by han-k59** [comment]
Yes should be no problem.  

On which system does Android run on X86?

**Comment by artyom-beilis** [comment]
These are latest android platforms: `arm64-v8a  armeabi-v7a  x86  x86_64`

Simulators are usually x86 - you build it for two arm platforms 64 and 32 bits.

**Comment by han-k59** [comment]
It compiled for Android X86 (i386) and X86_64 without any problem. All versions are available here.

http://www.hnsky.org/astap.htm#beta_version

**Comment by artyom-beilis** [comment]
> It compiled for Android X86 (i386) and X86_64 without any problem. All versions are available here.
> 
> http://www.hnsky.org/astap.htm#beta_version

I tested x86 and arm64-v8a - work ok!

In all I replaced the interpreter with one of below according if it is 64 or 32 bit

```
patchelf --set-interpreter /system/bin/linker astap_cli
patchelf --set-interpreter /system/bin/linker64 astap_cli
```
