### ISSUE TITLE
Database range update for astap_cli solver

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#49]
Update:

Database selection criteria:

old
 D50      (10 > fov > 0.2 degrees)
 D20      (10 > fov > 0.3 degrees) 
 D05      (10 > fov > 0.6 degrees) 
 G05      (20 > fov > 3.0 degrees) 
 W08      (       fov > 20 degrees) 

new:
 D50      (6 > fov > 0.2 degrees)
 D20      (6 > fov > 0.3 degrees) 
 D05      (6 > fov > 0.6 degrees) 
 G05      (20 > fov > 3.0 degrees) 
 W08      (       fov > 20 degrees) 

The database ranges are pretty wide.  ASTAP generates  a warning "Large FOV, Use G05 database" if FOV>6 degrees, but the auto selection was using the G05 database only for FOV>10. This resulted in a warning for people with a FOV  between 6 and 10 degrees. I have changed the auto selection of the G05 to FOV >6. So selection and warning are now both using the same 6 degrees as criteria.

1) So this would required an update in the documentation
2) Update of the executables.

Since OpenLiveStacker doesn't pass on the ASTAP warning this update has no priority. But if you do it do both point 1) and 2)  SourceForge contains the updated executables.

Han

**Comment by artyom-beilis** [comment]
Thanks, I'll update

**Comment by han-k59** [comment]
I have returned them!

Sorry. I did remove them to reduce the data amount but forgot they are used by your program.

Cheers, Han

**Comment by han-k59** [comment]
There is also a newer version of the command solver. This one is a little faster. But please check it.

**Comment by artyom-beilis** [comment]
Thanks a lot. I'll check it!

**Comment by artyom-beilis** [comment]
Hello, all work but this is still missing: g05_star_database.zip

**Comment by han-k59** [comment]
Strange. Pretty sure I have uploaded it a few weeks ago. I have uploaded it again. Should be okay now.

Cheers, Han

**Comment by artyom-beilis** [comment]
> Strange. Pretty sure I have uploaded it a few weeks ago. I have uploaded it again. Should be okay now.

Only g05 was missing yesterday - the rest where on SF.

**Comment by artyom-beilis** [comment]
And thanks! now it works!
