### ISSUE TITLE
Support Long Exposure Noise Reduction in DSLRs

### ISSUE THREAD

**Issue by flyingbarron** [artyom-beilis/OpenLiveStacker#65]
Some DSLRs have a feature generically called "Long Exposure Noise Reduction"

What this means is that after every image the camera will automatically take a dark frame and subtract it.

The benefit of this over traditional dark frames is that each frame will have a dark which is perfectly matched to the current temperature of the camera.
The disadvantage of this over traditional dark frames is that it doubles the time needed to collect the same amount of light.

I'd suggest a relatively low priority for this issue.

**Comment by artyom-beilis** [comment]
I assume this exists on capture level - so you configure the camera and it returns the image without darks on capture.

So maybe no need to do anything for this.

I'll close it meanwhile because the backlog is overloaded. I want it to be more concentrated on existing more urgent issues.
