### ISSUE TITLE
Solver, database not found

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#7]
The log says the solver database should be at:
/storage/emulated/0/DCIM/OpenLiveStacker/db  

But there are no files there and ASTAP reports no database found. See attached logs

[OpenliveStacker4.zip](https://github.com/artyom-beilis/OpenLiveStacker/files/11326879/OpenliveStacker4.zip)

**Comment by artyom-beilis** [comment]
You need to download and unpack one: https://github.com/artyom-beilis/OpenLiveStacker/wiki/Open-Live-Stacker-Manual#setting-up-plate-solver-on-andoid

**Comment by han-k59** [comment]
The size of the installer gave the impression it was included.

Better to add a database check to the app. For the case the database is not found give a warning with a clear instruction what to do to install it. Or easier if no .ini is found, give the warning with the instruction.

**Comment by artyom-beilis** [comment]
> if no .ini is found, give the warning with the instruction.

It should not happen under normal conditions. If no ASTAP exe is present I warn about it in specific error message. The missing DB is actually from ini file.

> The size of the installer gave the impression it was included

It is mostly OpenCV for x86, x86\_65, arm64-v8a and armeabi-v7 architectures. Next in line is CppCMS - the web framewrok.

I think actually on disk installation is much smaller as only relevant native libraries are extracted.

> with the instruction to unpack the database at that location. 

It is good idea to refer to the manual
