### ISSUE TITLE
DSLR no preview on Android

### ISSUE THREAD

**Issue by laheller** [artyom-beilis/OpenLiveStacker#72]
Hi @artyom-beilis 

I am testing the **OpenLiveStacker Beta 23** Android application using my **Samsung Galaxy S20+** smartphone and **Canon EOS 1300D** camera. When I just compare the app UI behaviour if I use my **ZWO ASI120MC-S** camera instead of Canon, I can see live preview on the UI when I tap on the Stream button. But in case of Canon camera when I tap on Stream button, there is no preview, the app only starts some lens autofocus and display a message (see the attached screenshot below).
Also when I try to select the camera from list, I would expect to see its name (e.g. Canon EOS 1300D) instead of just "Camera".
See some attached screenshots, hope they helps.

![Screenshot_20230925_082642](https://github.com/artyom-beilis/OpenLiveStacker/assets/5788998/4d66e118-fddd-4ea2-bc98-c70f29f527a7)

![Screenshot_20230925_082336](https://github.com/artyom-beilis/OpenLiveStacker/assets/5788998/dabb0310-5874-41d6-b081-3d6e4d356f0b)

BR,

Ladislav

**Comment by artyom-beilis** [comment]
HI.

Make sure that camera is in the manual mode also afair focus in manual as well

**Comment by artyom-beilis** [comment]
AutoStretch just makes sure that image isn't too dark. It is ols post-processing 

Viewfinder when checked brings the mirror up so it doesn't move each time image capture is triggered. It is dslr specific 

Now first time you connect to camera it does test capture to see supported formats and sizes (if raw is enabled etc).

When you press stream it start capturing images and streaming them to the ols screen. 

Note: images aren't saved at sd card or camera. They are deleted after downloading

**Comment by laheller** [comment]
> AutoStretch just makes sure that image isn't too dark. It is ols post-processing
> 
> Viewfinder when checked brings the mirror up so it doesn't move each time image capture is triggered. It is dslr specific
> 
> Now first time you connect to camera it does test capture to see supported formats and sizes (if raw is enabled etc).
> 
> When you press stream it start capturing images and streaming them to the ols screen.
> 
> Note: images aren't saved at sd card or camera. They are deleted after downloading

@artyom-beilis 

OK, now the meaning of settings is clear.
Also it is clear, how it works in case of DSLR:
Once tap on Stream button, it immediately start to take series of images using the configured ISO, shutter speed, etc. 

But in my case the camera (Canon EOS 1300D) does NOT support the mirror lockup function, so when before Stream I enable the Viewfinder checkbox, I hear the "mirror up" noise from camera body and its display will be turned off. When the Streaming starts, the mirror will be alternating once up once down when taking photos.

According to the OLS documentation the **streaming** function is NOT the livestacking itself, or am I wrong? It's just a camera picture preview. If so, then I would expect to bring camera into kind of "video mode" and display the video frames in OLS streaming mode.

BR,

Ladislav

**Comment by artyom-beilis** [comment]
> According to the OLS documentation the streaming function is NOT the livestacking itself, or am I wrong? 

You are correct. When live streaming is active you can start/stop live stacking 

>  I would expect to bring camera into kind of "video mode" 

Because you configure everything in stream mode so you want it to be same as actual stacking
