### ISSUE TITLE
Altair camera (GPCAM ARO130C) fails with AwbOnce

### ISSUE THREAD

**Issue by bilkusg** [artyom-beilis/OpenLiveStacker#73]
When I try to use my Altair ARO130C (Toupcam under the hood) Toupcam_AwbOnce fails, as I believe this call is not supported for this camera. Commenting out the failure and reporting it as a warning and recompiling appears to work.
Issue exists in Android and Raspberry Pi builds, and probably others but haven't tried them yet,

**Comment by artyom-beilis** [comment]
Is it color camera?  I think I didn't tested it with color camera yet.

I'll check it in few days. I'll probably need your cooperation to do accurate testing 

Thanks!

**Comment by artyom-beilis** [comment]
One more question. How did you get into ols? I mean were did you hear about it?

**Comment by artyom-beilis** [comment]
Hi, I pushed the change can you please check on Raspberry PI? I also added manual WB option. Please tell me if it is working as expected.

**Comment by artyom-beilis** [comment]
If it works I want to release Android version

**Comment by bilkusg** [comment]
Hi sorry not to have replied sooner I've been busy the last few days. I will test this this evening. Many thanks for the prompt fix. I heard about the app via a search on stargazers-lounge for eaa options.

**Comment by artyom-beilis** [comment]
> I can confirm that the app compiles on my pi and will now open the camera and display a stream

Nice, does manual auto WB can be turned on off? Manual WB with setting light temperature works?

**Comment by artyom-beilis** [comment]
Closing this issue. If you encounter other problems feel free to reopen, fixed in 64eff44333ec590e2aba91fb4878166e4d43d26a
