### ISSUE TITLE
Feature request: Support for FITS

### ISSUE THREAD

**Issue by petmos** [artyom-beilis/OpenLiveStacker#74]
KStars/EKOS can create images in FITS format. It would be fine if you could add support for this format.
In this it would be possible to have live stacking during a KStars session.

**Comment by artyom-beilis** [comment]
> KStars/EKOS can create images in FITS forma

I thought it was possible to create images in raw or tiff format that OLS supports...

I need to check for existing libraries to read FITS

**Comment by bilkusg** [comment]
I would support this request. Although Ekos supports various raw formats, on some cameras, it doesn't actually download reliably unless you use fits, so this would be a nice to have option. And since fits gives you lots of metadata it makes it easier to choose as the program can work out most of the parameters for itself.

**Comment by artyom-beilis** [comment]
One more question. OLS nowadays supports quite lots of cameras, ASI,, ToupTek, UVC based and even DSLR.

What camera do you have that you want to connect it to OLS via file system?

**Comment by petmos** [comment]
I'm using an ASI224MC and hopefully an ASI533MC Pro in the near future.
In addition, I also use KStars and would like to continue using FITS.
At the moment I'm using a converter fitstopng. That works also.
But my results are always grayscale, no colours.

**Comment by artyom-beilis** [comment]
I suggest till FITs support is going to be implemented connect your ASI camera directly to OpenLiveStacker (i.e. build with ASI ZWO SDK) it would be much more efficient

**Comment by han-k59** [comment]
If Astro-Tiff is implemented it could be a substitute. You have then the full "FITS" header in Tiff. That is likely easier to implement since OpenLivestacker already writes Tiff. 
See:
https://github.com/artyom-beilis/OpenLiveStacker/issues/5

Han

**Comment by Pti-Jean** [comment]
(Message translated into English)
I am also interested in adding functionality that supports .fits ... I use a ZWO ASI533MC color camera ...

(Original message in French)
Je suis aussi intéressé par l'ajout de la fonctionnalité qui prend en charge le format .fits ... J'utilise une caméra couleur ZWO ASI533MC...

**Comment by artyom-beilis** [comment]
Implemented in 4fc4d39ee198266d7986f65d361ef8b8c93c210d
