### ISSUE TITLE
ASTAP_CLI latest executables are not working

### ISSUE THREAD

**Issue by han-k59** [artyom-beilis/OpenLiveStacker#79]
Hi Artik,

I get feedback that the latest astap_cli for Android is not working. The file type seems wrong. However it is working in BlueStack emulation. See this issue:

https://github.com/han-k59/astap/issues/1

Questions:
  Have you tried a newer astap_cli and did it work?
  The current astap_cli in your app. If this astap_cli is tested in Linux what does the command: "file ./astap_cli" report?
  What is the astap_cli location in an android phone with your app installed?

Thanks, Han

**Comment by artyom-beilis** [comment]
Not relevant
