### ISSUE TITLE
Meade DSI original gets "strange error-

### ISSUE THREAD

**Issue by blp042** [artyom-beilis/OpenLiveStacker#83]
I tried my original (old) Meade DSI and got the error below.
![Screenshot_20240109-212956](https://github.com/artyom-beilis/OpenLiveStacker/assets/862560/314020b6-c80a-4fa1-802b-1e7c79c10222)

**Comment by artyom-beilis** [comment]
The supported Mead - touptek based cameras can be found there:

https://github.com/artyom-beilis/OpenLiveStacker/blob/main/src/toup_oem.h#L63

From product-id/vendor-id it seems not to be in the list. 

Does this camera work with indi/touptek driver?

**Comment by blp042** [comment]
It does not. Must be another INDI driver because it works on AstroBerry, EKOS, PHD2, StellarMate.
No worries. I'd just like mine to work. I love the possibility it might work on Android phones though.
Great work. I may try to compile it myself and see if I can add support.

**Comment by flyingbarron** [comment]
If it's the original DSI then it's probably a webcam type camera.
@blp042 What camera type have you tried? Do you get a different error when you choose UVC?

**Comment by blp042** [comment]
Thanks for the attention.  Trying UVC with Meade DSI gives me this error:

**Comment by flyingbarron** [comment]
I don't see an error. I think the screenshot didn't load.

**Comment by blp042** [comment]
I just sent again.

**Comment by blp042** [comment]
Failed to wrap fd:Invalid device

**Comment by blp042** [comment]
Camera name was "camera_0"
I was asked to grant permission to use that device.

**Comment by flyingbarron** [comment]
Hmm.... doing a bit of reading, it looks like DSI is a Meade specific camera family and neither the UVC nor the ToupTek drivers will work for them.
It's a completely different set of drivers and @artyom-beilis would need to develop new integration for this camera. 

I assume this is what Indi is using:
https://github.com/indilib/indi-3rdparty/tree/master/indi-dsi

**Comment by artyom-beilis** [comment]
> I assume this is what Indi is using:
> https://github.com/indilib/indi-3rdparty/tree/master/indi-dsi

It looks like indi implemented its own driver over libusb directly instead of using their SDK. That means basically converting their code to open-live-stacker driver.

Good: it means no need to wait for Meade to release android SDK
Bad: it quite lots of work and not something that can be done without real camera to test.

Sorry `:-)`

**Comment by artyom-beilis** [comment]
Closing as not something that can be supported at this point.

**Comment by blp042** [comment]
Thanks for looking anyway.
Is there a website showing succesful image acquisitions and stacking along
with camera info? I am not opposed to buying a camera, one that doesn't
cost too much. I just bought a Seestar S50 in December.

**Comment by artyom-beilis** [comment]
You mean examples of stacked images?

Here is a thread I share my images with very simple equipment: https://www.cloudynights.com/topic/882728-eaa-with-simple-achromat-way-better-than-you-can-think-of/ (I don't mention OLS due to forum restrictions of not promoting stuff)

Here little bit more info in this development thread on the forum: https://www.cloudynights.com/topic/875680-openlivestacker-getting-ready-for-google-play-discussions/

**Comment by blp042** [comment]
Yes. Along with the camera used. I would like to try my success with a
camera known to work already.

**Comment by artyom-beilis** [comment]
> Yes. Along with the camera used. I would like to try my success with a camera known to work already.

Basically look at list of supported cameras: 

- ASI ZWO - most popular cameras used with OLS and most tested in my opinion
- ToupTek - I know of several cameras working
- Android Camera
- SVBony sv105, sv205 generally
- DSLR/DSLM - as long as they are supported by libgphoto and have trigger capture mode

But of course remember disclaimer the software comes without any kind of warranty :-)
