### ISSUE TITLE
PI Installation

### ISSUE THREAD

**Issue by 12nucleus** [artyom-beilis/OpenLiveStacker#88]
Anyone has the instructions on how to install OLS on the Raspberry PI?  I have a Pi 4, 4Gb but it just refuses to compile properly.

High five to the developer!! I have been using OLS on Android and just love its simplicity, live stacking feature and plate solving to find my targets.

**Comment by artyom-beilis** [comment]
Yes they are in Read me, pretty straight forward:

https://github.com/artyom-beilis/OpenLiveStacker?tab=readme-ov-file#using-on-linux

I think the only tricky thing that I've seen on Pi is to select correct library in SDK - check if it is 32 or 64 bit.

What problems do you get?

**Comment by 12nucleus** [comment]
**This is what I get when I follow the Linux install instructions:**

stellarmate@stellarmate:~/tools/OpenLiveStacker/build $ cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ASTAP DB Download enabled
CPU: aarch64
- OpenCV Include Path /usr/include/opencv4
- No ASI SDK header/lib found
- No Toupcam SDK header/lib found
- Building UVC Driver
- Building WDir driver with libraw
- Building GPhoto2 Driver with libraw
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBBOOSTER
    linked by target "ols" in directory /home/stellarmate/tools/OpenLiveStacker
    linked by target "ols_driver_wdir" in directory /home/stellarmate/tools/OpenLiveStacker
LIBCPPCMS
    linked by target "ols" in directory /home/stellarmate/tools/OpenLiveStacker
LIBCPPCMS_HRD
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker
   used as include directory in directory /home/stellarmate/tools/OpenLiveStacker

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ols":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ols_driver_uvc":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ols_driver_sim":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ols_driver_wdir":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ols_driver_gphoto2":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "test_camera":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "ols_cmd":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "offline_ols":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "ols_plate_solver_test":

    "LIBCPPCMS_HRD-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by artyom-beilis** [comment]
Two things

Run `./build/ols_cmd config.json`

2nd to use touptek set driver to value "toup"

**Comment by artyom-beilis** [comment]
Also note in previous comment:

> No Toupcam SDK header/lib found

You need to download touptek SDK and provide path to it as per instructions - make sure you match arch (32 or 64 bit) to the library

**Comment by 12nucleus** [comment]
Made some progress but still have issues with the driver.

I can start OLS if I dont put any driver in the config file. When I add 'toup', OLS says it is looking for libols_driver_toup.so instead of the default driver name in the SDK libtoupcam.so. If I rename the driver to libols_driver_toup.so and run ols, I get this error:

./build/ols_cmd config.json 
failed:Failed to load driver /home/stellarmate/tools/OpenLiveStacker/build/libols_driver_toup.so: `/home/stellarmate/tools/OpenLiveStacker/build/libols_driver_toup.so: wrong ELF class: ELFCLASS32'

Also, I dont see any arch 32 or 64 bit option in the SDK library, just arm64  armel  armhf  udev  x64  x86. 

I tried both the arm64 and armhf driver without success.

My config.json:

{
    "libdir" : "/home/stellarmate/tools/OpenLiveStacker/build",
    "driver" : "toup",
    "astap" : {
        "exe": "astap_cli",
        "db": "/home/stellarmate/tools/OpenLiveStacker/build/data/db"
    },
    "http": {
        "ip":"0.0.0.0",
        "port":8080
    }
}


Thanks a ton for you support!

**Comment by artyom-beilis** [comment]
>  OLS says it is looking for libols_driver_toup.so instead of the default driver name in the SDK libtoupcam.s

`libols_driver_toup.so` is the OLS driver linked to SDK libtoupcam.so. 

> `/home/stellarmate/tools/OpenLiveStacker/build/libols_driver_toup.so: wrong ELF class: ELFCLASS32'

Please print the output of

`ldd build/libols_driver_toup.so` 

and

`file build/libols_driver_toup.so`

It looks like something incorrect pointing to LD_LIBRARY_PATH or it loads libtoupcam from incorrect location

**Comment by 12nucleus** [comment]
stellarmate@stellarmate:~/tools/OpenLiveStacker $ ldd build/libols_driver_toup.so 
	not a dynamic executable

stellarmate@stellarmate:~/tools/OpenLiveStacker $ file build/libols_driver_toup.so 
build/libols_driver_toup.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=bdb12a0c5b8722bafebe9d12e4a98e26c822dee0, stripped

**Comment by artyom-beilis** [comment]
>  I wrongly assume that I needed to copy and rename libtoupcam.so to build/libols_driver_toup.so.

Absolutely... 

You need to add parameters to CMake:

    cmake -DCMAKE_INCLUDE_PATH=/path/to/toupteck_sdk/inc -DCMAKE_LIBRARY_PATH=/path/to/toupteck_sdk/linux/arm64 ..

Or if it is 32 bit pi/build than `armhf` or `armel` instead (not sure which one)

Than there should be a message : `- Building Toupcam Driver` in cmake output

**Comment by 12nucleus** [comment]
Still no go ... I tried arm64, armhf and armel with the same result. I get ' Building Toupcam Driver' with the cmake command but make does not go through.

cmake -DCMAKE_INCLUDE_PATH=/home/stellarmate/Downloads/toupcamsdk/inc -DCMAKE_LIBRARY_PATH=/home/stellarmate/Downloads/toupcamsdk/linux/arm64 ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ASTAP DB Download enabled
CPU: aarch64
- OpenCV Include Path /usr/include/opencv4
- No ASI SDK header/lib found
- Building Toupcam Driver
- Building UVC Driver
- Building WDir driver with libraw
- Building GPhoto2 Driver with libraw
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stellarmate/OpenLiveStacker/build




make
[  3%] Building CXX object CMakeFiles/ols_driver_toup.dir/src/toup_camera.cpp.o
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp: In constructor ‘ols::ToupcamCamera::ToupcamCamera(const std::string&, const std::string&, ols::CamErrorCode&)’:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:112:27: error: ‘Toupcam_query_Model’ was not declared in this scope; did you mean ‘Toupcam_put_Mode’?
  112 |             info_.model = Toupcam_query_Model(hcam_);
      |                           ^~~~~~~~~~~~~~~~~~~
      |                           Toupcam_put_Mode
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp: In member function ‘virtual std::vector<ols::CamOptionId> ols::ToupcamCamera::supported_options(ols::CamErrorCode&)’:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:517:37: error: ‘TOUPCAM_FLAG_HIGH_FULLWELL’ was not declared in this scope
  517 |             if (info_.model->flag & TOUPCAM_FLAG_HIGH_FULLWELL)
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:2:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp: In member function ‘virtual ols::CamParam ols::ToupcamCamera::get_parameter(ols::CamOptionId, bool, ols::CamErrorCode&)’:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:745:59: error: ‘TOUPCAM_OPTION_HIGH_FULLWELL’ was not declared in this scope; did you mean ‘TOUPCAM_OPTION_BLACKLEVEL’?
  745 |                 if (FAILED(hr = Toupcam_get_Option(hcam_, TOUPCAM_OPTION_HIGH_FULLWELL, &high_fullwell)))
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/stellarmate/Downloads/toupcamsdk/inc/toupcam.h:69:37: note: in definition of macro ‘FAILED’
   69 | #define FAILED(hr)      (((HRESULT)(hr)) < 0)
      |                                     ^~
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp: In member function ‘virtual void ols::ToupcamCamera::set_parameter(ols::CamOptionId, double, ols::CamErrorCode&)’:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:892:48: error: ‘TOUPCAM_OPTION_HIGH_FULLWELL’ was not declared in this scope; did you mean ‘TOUPCAM_OPTION_BLACKLEVEL’?
  892 |                 hr = Toupcam_put_Option(hcam_, TOUPCAM_OPTION_HIGH_FULLWELL, value ? 1 : 0);
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                TOUPCAM_OPTION_BLACKLEVEL
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp: In member function ‘void ols::ToupcamCamera::init(ols::CamErrorCode&)’:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:1107:39: error: ‘TOUPCAM_FLAG_HIGH_FULLWELL’ was not declared in this scope
 1107 |             if (((info_.model->flag & TOUPCAM_FLAG_HIGH_FULLWELL)) && FAILED(hr = Toupcam_put_Option(hcam_, TOUPCAM_OPTION_HIGH_FULLWELL, 1)))
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:1107:109: error: ‘TOUPCAM_OPTION_HIGH_FULLWELL’ was not declared in this scope; did you mean ‘TOUPCAM_OPTION_BLACKLEVEL’?
 1107 |             if (((info_.model->flag & TOUPCAM_FLAG_HIGH_FULLWELL)) && FAILED(hr = Toupcam_put_Option(hcam_, TOUPCAM_OPTION_HIGH_FULLWELL, 1)))
      |                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/stellarmate/Downloads/toupcamsdk/inc/toupcam.h:69:37: note: in definition of macro ‘FAILED’
   69 | #define FAILED(hr)      (((HRESULT)(hr)) < 0)
      |                                     ^~
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp: In member function ‘int ols::ToupcamCameraDriver::enumOEM(ToupcamDeviceV2*)’:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:1271:33: error: ‘Toupcam_get_Model’ was not declared in this scope; did you mean ‘Toupcam_get_Mode’?
 1271 |                 info[N].model = Toupcam_get_Model(0x547,tp_pid);
      |                                 ^~~~~~~~~~~~~~~~~
      |                                 Toupcam_get_Mode
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp: In function ‘void ols_set_toup_driver_log(const char*, int)’:
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:1332:9: error: ‘Toupcam_log_File’ was not declared in this scope; did you mean ‘Toupcam_put_Size’?
 1332 |         Toupcam_log_File(log_path);
      |         ^~~~~~~~~~~~~~~~
      |         Toupcam_put_Size
/home/stellarmate/OpenLiveStacker/src/toup_camera.cpp:1333:9: error: ‘Toupcam_log_Level’ was not declared in this scope
 1333 |         Toupcam_log_Level(debug ? 4 : 1);
      |         ^~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/ols_driver_toup.dir/build.make:76: CMakeFiles/ols_driver_toup.dir/src/toup_camera.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:101: CMakeFiles/ols_driver_toup.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by artyom-beilis** [comment]
Please download latest SDK - it seems you are using outdated SDK

Look here: https://www.touptek-astro.com/downloads/ go to For developers: ToupTek Astronomy camera SDK

**Comment by 12nucleus** [comment]
Wow, that was an ordeal! All working now. This is idiotic, when you google 'touptek sdk', the top result brings you to http://www.touptek.com/ with the older SDK.

Anyway, thanks for your patience and you help.
